### ISSUE TITLE
Question how to modify swaybar?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [JayceFayne/swayipc-rs#22]
I am working on something that changes the colorscheme for various programs based on the current time. I am struggling to find a way to set the swaybar with `swayipc-async = "2.0.0-alpha.2"`. I'd like to be able to do the equivalent sway config

```
bar {
   swaybar_command waybar -s /path/to/style.css
}
```

Is this possible?

**Comment by JayceFayne** [comment]
I don't know if you can change the swaybar_command at runtime but you can execute all commands defined in [sway.5.scd](https://github.com/swaywm/sway/blob/master/sway/sway.5.scd) (except config only ones) over swayipc using `Connection::run_command`. The commands specific to swaybar are documented in [sway-bar.5.scd](https://github.com/swaywm/sway/blob/master/sway/sway-bar.5.scd). This repo contains a [command_loop](https://github.com/JayceFayne/swayipc-rs/blob/master/examples/command_loop_async_std/src/main.rs) example if you need a starting point.

**Comment by Th3Whit3Wolf** [comment]
Alright, I didn't think that would work so I didn't try it. Thank you for the help!
