### ISSUE TITLE
Sporadic "failed to fill whole buffer" error from EventIterator::next() (using swayipc 2.7.2)

### ISSUE THREAD

**Issue by tsdh** [JayceFayne/swayipc-rs#26]
Hi all,

I use swayipc 2.7.2 in a hobby project of mine.  There, I have a demon subscribing to window and workspace events.  That's the function doing that:

```rust
pub fn monitor_sway_events(
    extra_props: Arc<RwLock<HashMap<i64, ipc::ExtraProps>>>,
) {
    let iter = s::Connection::new()
        .expect("Could not connect!")
        .subscribe(&[s::EventType::Window, s::EventType::Workspace])
        .expect("Could not subscribe to window and workspace events.");

    for ev_result in iter {
        let handled;
        match ev_result {
            Ok(ev) => match ev {
                r::Event::Window(win_ev) => {
                    let extra_props_clone = extra_props.clone();
                    handled = handle_window_event(win_ev, extra_props_clone);
                }
                r::Event::Workspace(ws_ev) => {
                    let extra_props_clone = extra_props.clone();
                    handled = handle_workspace_event(ws_ev, extra_props_clone);
                }
                _ => handled = false,
            },
            Err(e) => {
                eprintln!("Error while receiving events: {}", e); // <== Here the error is reported
                handled = false;
            }
        }
        if handled {
            println!(
                "New extra_props state:\n{:#?}",
                *extra_props.read().unwrap()
            );
        }
    }
}
```

It sometimes happens that after working fine for hours, I get an "failed to fill whole buffer" error reported at the marked line, so it must come from `EventIterator::next()`, I guess.

When that error happens, the iterator won't recover, i.e., the loop continues and spills gazillions of error lines to stderr.  According to the swayipc event_printer example, my code seems to follow the advertised usage conventions.  But maybe I should improve it by creating a new `Connection` and subscribing again once an error has been reported from the `EventIterator`?  Or are there certain errors where the iterator can recover?

I'm running the current master branches of sway and wlroots updated daily.

**Comment by JayceFayne** [comment]
Hey, I have a few comments regarding this error

> It sometimes happens that after working fine for hours, I get an "failed to fill whole buffer" error reported at the marked line, so it must come from EventIterator::next(), I guess.

A backtrace from where this error originates would be nice^^

>  But maybe I should improve it by creating a new Connection and subscribing again once an error has been reported from the EventIterator?

This is certainly a valid workaround. Still, it would be nice to know what causes this error, I am using this library as well in order to subscribe to `Window` and `Workspace` events and I have not encountered this error yet

> I'm running the current master branches of sway and wlroots updated daily.

Hmmm, this might be a problem since I target the latest stable release with this library [see](https://github.com/JayceFayne/swayipc-rs/blob/master/README.md). Although looking at the commit history...it does seem highly unlikely that any recent commit on sway's side caused this error

**Comment by tsdh** [comment]
@JayceFayne I already run my demon using `env RUST_BACKTRACE=1 swayrd` but that only kicks in when panicking, I think. How do I print the stacktrace in the `Err(err) => ...` match arm when handling the error?  There's [Error::backtrace](https://doc.rust-lang.org/nightly/std/error/trait.Error.html#method.backtrace) but that's a nightly-only experiment and I am targeting stable rust.

**Comment by JayceFayne** [comment]
Removing the outer `match` and using `ev_result.unwrap()` in the inner one should do the trick

**Comment by tsdh** [comment]
Ok, then it would be panicking and print the backtrace but my demon would crash.

Well, if I had some workable reproduction recipe, I'd immediately do it, but I haven't.  The issue only occurred three times and only at my work computer where I run the cargo-installed binaries of my crate.

Today I've used two forks and a bottle to press a shortcut and keep it pressed which executes a command from my crate which cycles through all windows of all workspaces, so window and workspace events at keyboard repeat rate.  I've kept it for at least 30 minutes but no error occurred.

**Comment by JayceFayne** [comment]
> Ok, then it would be panicking and print the backtrace but my demon would crash.

Yes, it would crash and print out the backtrace

> Well, if I had some workable reproduction recipe, I'd immediately do it, but I haven't. The issue only occurred three times and only at my work computer where I run the cargo-installed binaries of my crate.

I was able to reproduce this error by executing the [event printer example](https://github.com/JayceFayne/swayipc-rs/tree/master/examples/event_printer) from a terminal, detaching the process and then logging out of sway. This would consistently yield `Error: UnixStreamIO(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })` because the IPC server (sway) is shutting down. Unless this error happens outside of the situation I just described I would not consider it an issue

**Comment by tsdh** [comment]
The error happened to me in normal sway sessions, i.e., sway was not shutting down.  And I could kill and restart my demon without issues and then it was able to receive events again.

Well, I've improved my code so that a new connection will be started if I get an error from the event iterator.  And it seems that I've haven't had that error in the last few days.  I'll keep the issue open for another week, and if it doesn't happen again, I'll just blame some bad revisions in sway master.

**Comment by tsdh** [comment]
@JayceFayne Ah, sorry not reporting back after "another week".  I haven't gotten that error since I've reported the issue and use swayipc the whole day (3.0.0-alpha.3 nowadays, though).

**Comment by JayceFayne** [comment]
Don't worry about it :D Thanks for reporting back that everything works smoothly on the latest alpha!
