### ISSUE TITLE
unresolved import `swayipc::Event`

### ISSUE THREAD

**Issue by dpgraham4401** [JayceFayne/swayipc-rs#28]
I tried  to run the [./examples/hovered_window](https://github.com/JayceFayne/swayipc-rs/blob/master/examples/hovered_window/src/main.rs) example, and I got the following error. 

```
error[E0432]: unresolved import `swayipc::Event`
 --> src/main.rs:1:27
  |
1 | use swayipc::{Connection, Event, EventType, Fallible};
  |                           ^^^^^
  |                           |
  |                           no `Event` in the root
```

Do  we need to update the examples or am I just a numb nuts? :)

**Comment by JayceFayne** [comment]
It seems like you are using the latest stable version of `swayipc`. 
The examples in master work with the latest alpha. 
Try replacing your current import with
```
use swayipc::reply::Event;
use swayipc::{Connection, EventType, Fallible};
```
It should fix the import error ;)

**Comment by dpgraham4401** [comment]
Yup, that's it! Thanks for the work you do!
