### ISSUE TITLE
Node structure seems to be missing floating property

### ISSUE THREAD

**Issue by madhur** [JayceFayne/swayipc-rs#44]
I have been using swayipc in my application. It works really well. Thank you for this library.

I have faced on blocker though, I am looking to know if the node is floating or not. There is property exposed by i3 called `floating` which seems to be missing.

Its documented here
https://i3wm.org/docs/ipc.html#_tree_reply

```
floating (string)

    Floating state of container. Can be either "auto_on", "auto_off", "user_on" or "user_off"
```

**Comment by JayceFayne** [comment]
Hi there!

This property is indeed missing. But for your particular use case you can identify floating nodes by looking at `node_type` property on a `Node` . The `NodeType` enum contains a variant named `FloatingCon` which indicates that this particular Container/Node is floating

**Comment by madhur** [comment]
I agree. However, I believe there must be some different nuances. For example by looking at `NodeType` property, you cannot tell if the window was floating from beginning or was made later by user.

**Comment by JayceFayne** [comment]
That's true,  I can provide a PR but since I don't use i3 anymore I am unable to test it

**Comment by madhur** [comment]
I will test it out.
