### ISSUE TITLE
No `Workspace::leaves` method

### ISSUE THREAD

**Issue by I60R** [JayceFayne/swayipc-rs#46]
This exists in Python's `i3ipc` and returns a `Vec` over windows assigned to workspace

**Comment by madhur** [comment]
Python's module calculates it and exposes it as method. There is no inbuilt method in i3 protocol to retrieve all the leaves of all workspaces.

**Comment by I60R** [comment]
Ok

```rust
    let mut workspaces: Vec<_> = outputs.as_slice().iter()
        .flat_map(|outputs| outputs.nodes.as_slice())
        .filter(|workspace| workspace.name.as_deref() != Some("__i3_scratch"))
        .collect();
```

did the job
