### ISSUE TITLE
async-pidfd -> async_process

### ISSUE THREAD

**Issue by MaxVerevkin** [JayceFayne/swayipc-rs#52]
`async-pidfd` is unmaintained and pulls the `async-io` v1 dependency, while the main project depends on v2.

**Comment by JayceFayne** [comment]
That's unfortunate. I see you have opened a PR https://github.com/joshtriplett/async-pidfd/pull/4, would be nice if it was merged...irrc I initially used `async-process` but switched to `async-pidfd` because it has less dependencies

**Comment by JayceFayne** [comment]
@MaxVerevkin maybe we should fork async-pidfd?

**Comment by MaxVerevkin** [comment]
I can publish my fork so you can switch over to it, if that's what you mean.

**Comment by JayceFayne** [comment]
Yeah

**Comment by joshtriplett** [comment]
I've updated `async-pidfd` to incorporate all of those changes, and published async-pidfd 0.1.5. I hope that helps.
