### ISSUE TITLE
Node::iter() doesn't consider floating nodes

### ISSUE THREAD

**Issue by tsdh** [JayceFayne/swayipc-rs#53]
I'm using this crate in my [swayr](https://sr.ht/~tsdh/swayr/) tool and love it.  Thanks, a lot!

Due to [this bug report](https://todo.sr.ht/~tsdh/swayr/42) I just found out that `Node::iter()` doesn't consider floating nodes.  Before working around that on my side, I just wanted to ask if that is an oversight (`self.queue.extend(result.floating_nodes.iter());` missing in the impl) or the intended behavior.  In the latter case, could you please add another iterator methods for all and only floating nodes?

**Comment by JayceFayne** [comment]
Ooops, I completely missed this when I reviewed #49 😅

**Comment by tsdh** [comment]
Great, thank you!

**Comment by tsdh** [comment]
If it's not too much effort, I'd be very happy if you could publish a new `swayipc-types` version to crates.io so that I can update the dependency in swayr.  Otherwise, I'll work around it on my side until a new version is released.

**Comment by JayceFayne** [comment]
Yeah, definitely wanted to publish a new version. I think I'll manage to do so this weekend. Just didn't have the time yet😄

**Comment by tsdh** [comment]
Perfect, thank you.

**Comment by JayceFayne** [comment]
Published swayipc-types v1.3.2 🎉

**Comment by tsdh** [comment]
Paaaaarty! :-)
